-- ═══════════════════════════════════════════════════════════════════
-- Dentico Finance — complete Supabase installation
-- AUTO-GENERATED by scripts/build-install-sql.mjs — do not edit by hand.
--
-- Supabase Dashboard → SQL Editor → New query → paste → Run.
-- Safe to run more than once (all statements are idempotent).
--
-- Objects created:
--   • SCHEMA — tables, indexes, triggers, RLS
--   • SEED — coa_accounts (chart of accounts)
--   • SEED — finance_monthly + finance_overview_meta
--   • SEED — journals + journal_lines
--   • SEED — gl_supplements
--   • SEED — pnl_account_postings
-- ═══════════════════════════════════════════════════════════════════

-- ══════════════════════════════════════════════════════════════════
-- [1/6] SCHEMA — tables, indexes, triggers, RLS
-- source: supabase/schema.sql
-- ══════════════════════════════════════════════════════════════════
-- ═══════════════════════════════════════════════════════════════════
-- Dentico Finance — Chart of Accounts schema
-- Run this in your Supabase project (SQL Editor) before seed.sql
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.coa_accounts (
  id           uuid primary key default gen_random_uuid(),
  code         text not null unique,                -- e.g. "1103"
  name         text not null,                       -- e.g. "Bank BSI Giro Utama"
  type_label   text not null default '',            -- e.g. "Aset Lancar (Bank)"
  group_code   text not null,                       -- top-level header: 1000..6600
  parent_code  text,                                -- parent account code (level 2 parents)
  parent_label text,                                -- denormalised "1100 - Kas & Setara Kas"
  normal       text not null default 'Debit' check (normal in ('Debit','Kredit')),
  is_header    boolean not null default false,      -- header accounts cannot be posted to
  can_post     boolean not null default true,       -- level-2 posting accounts
  is_active    boolean not null default true,
  is_locked    boolean not null default false,      -- has ledger history → protected
  tx_count     integer not null default 0,
  updated_at   timestamptz not null default now()
);

create index if not exists coa_accounts_group_idx  on public.coa_accounts (group_code);
create index if not exists coa_accounts_active_idx on public.coa_accounts (is_active);

-- Keep updated_at fresh on writes
create or replace function public.touch_coa_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

drop trigger if exists trg_coa_touch on public.coa_accounts;
create trigger trg_coa_touch
  before update on public.coa_accounts
  for each row execute function public.touch_coa_updated_at();

-- Row Level Security: read for everyone, writes for authenticated roles.
alter table public.coa_accounts enable row level security;

drop policy if exists "coa read" on public.coa_accounts;
create policy "coa read" on public.coa_accounts for select using (true);

drop policy if exists "coa write" on public.coa_accounts;
create policy "coa write" on public.coa_accounts for all
  using (true) with check (true);

-- ═══════════════════════════════════════════════════════════════════
-- Executive Overview snapshots (read-only analytics, posted by ledger)
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.finance_monthly (
  id             text primary key,             -- '2026-09'
  month_label    text not null,                -- 'Sep'
  month_label_long text not null default '',   -- 'September 2026'
  revenue        numeric not null default 0,
  hpp            numeric not null default 0,
  opex           numeric not null default 0,
  net_profit     numeric not null default 0
);

alter table public.finance_monthly enable row level security;
drop policy if exists "finance monthly read" on public.finance_monthly;
create policy "finance monthly read" on public.finance_monthly for select using (true);

create table if not exists public.finance_overview_meta (
  id      boolean primary key default true check (id),   -- singleton row
  payload jsonb not null
);

alter table public.finance_overview_meta enable row level security;
drop policy if exists "finance meta read" on public.finance_overview_meta;
create policy "finance meta read" on public.finance_overview_meta for select using (true);

-- ═══════════════════════════════════════════════════════════════════
-- Jurnal Umum & Entry (dual-entry engine)
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.journals (
  id                uuid primary key default gen_random_uuid(),
  number            text not null unique,          -- 'JV/2026/09/0142'
  date              date not null,
  journal_type      text not null default 'JU',    -- JU/JP/JB/KM/KK/BK/ADJ
  brand             text not null,
  branch            text not null,
  reference         text not null default '',
  description       text not null default '',
  total             numeric not null default 0,
  status            text not null default 'DRAFT'
                    check (status in ('DRAFT','REVIEW','APPROVED','POSTED')),
  operator_name     text not null,
  operator_role     text not null default '',
  operator_initials text not null default '',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);

create index if not exists journals_status_idx on public.journals (status);
create index if not exists journals_date_idx   on public.journals (date);

create table if not exists public.journal_lines (
  id           uuid primary key default gen_random_uuid(),
  journal_id   uuid not null references public.journals(id) on delete cascade,
  line_no      integer not null,
  account_code text not null,
  account_name text not null,
  memo         text not null default '',
  debit        numeric not null default 0,
  credit       numeric not null default 0,
  -- Natural key so re-running install.sql replaces lines instead of
  -- duplicating them (the bare `id` uuid can never conflict).
  unique (journal_id, line_no)
);

create index if not exists journal_lines_journal_idx on public.journal_lines (journal_id);

-- `create table if not exists` above is a no-op when the table already exists,
-- so an older install would never pick up the (journal_id, line_no) unique
-- key. Add it separately when missing — without this, re-running install.sql
-- would duplicate every journal line.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'journal_lines_journal_id_line_no_key'
  ) then
    alter table public.journal_lines
      add constraint journal_lines_journal_id_line_no_key unique (journal_id, line_no);
  end if;
end $$;

alter table public.journals enable row level security;
drop policy if exists "journals rw" on public.journals;
create policy "journals rw" on public.journals for all using (true) with check (true);

alter table public.journal_lines enable row level security;
drop policy if exists "journal lines rw" on public.journal_lines;
create policy "journal lines rw" on public.journal_lines for all using (true) with check (true);

-- ═══════════════════════════════════════════════════════════════════
-- Buku Besar (General Ledger)
-- Live movements derive from posted journals (view), plus immutable
-- upstream supplement postings (POS batch, payroll, QRIS clearing).
-- ═══════════════════════════════════════════════════════════════════

create or replace view public.gl_account_movements as
select
  jl.account_code,
  j.number        as voucher,
  j.date,
  j.brand,
  j.branch,
  j.reference,
  j.description,
  jl.memo,
  jl.debit,
  jl.credit,
  j.id            as journal_id
from public.journal_lines jl
join public.journals j on j.id = jl.journal_id
where j.status = 'POSTED';

create table if not exists public.gl_supplements (
  id           uuid primary key default gen_random_uuid(),
  ref_id       text not null unique,             -- 's-1103-01'
  account_code text not null,
  date         date not null,
  time         text not null default '09:00',
  voucher      text not null,
  ref          text not null default '',
  branch       text not null,
  dot          text not null default 'primary',
  description  text not null,
  sub_desc     text,
  offset_label text not null,
  debit        numeric not null default 0,
  credit       numeric not null default 0,
  bukti        text not null default 'receipt',
  memo         text
);

create index if not exists gl_supplements_account_idx on public.gl_supplements (account_code);

alter table public.gl_supplements enable row level security;
drop policy if exists "gl supplements read" on public.gl_supplements;
create policy "gl supplements read" on public.gl_supplements for select using (true);

-- ═══════════════════════════════════════════════════════════════════
-- Laba Rugi — aggregated per-account periodic postings
-- (ditulis oleh ledger rollup engine; view-nya ada di laporan)
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.pnl_account_postings (
  id     uuid primary key default gen_random_uuid(),
  seq    integer not null,
  code   text not null,
  period text not null,                -- '2026-09'
  amount numeric not null default 0,
  tag    text,
  unique (code, period)
);

create index if not exists pnl_postings_period_idx on public.pnl_account_postings (period);

alter table public.pnl_account_postings enable row level security;
drop policy if exists "pnl read" on public.pnl_account_postings;
create policy "pnl read" on public.pnl_account_postings for select using (true);

-- ══════════════════════════════════════════════════════════════════
-- [2/6] SEED — coa_accounts (chart of accounts)
-- source: supabase/seed.sql
-- ══════════════════════════════════════════════════════════════════
-- AUTO-GENERATED by scripts/generate-seed-sql.mjs — do not edit by hand.
-- Seeds the coa_accounts table with the Dentico dummy dataset
-- (115 accounts: 6 headers + 109 posting accounts).

insert into public.coa_accounts
  (code, name, type_label, group_code, parent_code, parent_label, normal, is_header, can_post, is_active, is_locked, tx_count, updated_at)
values
  ('1000', 'ASET', 'Header Aset', '1000', NULL, NULL, 'Debit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('1101', 'Kas Kecil', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 210, '2026-09-22T09:00:00+07:00'),
  ('1102', 'Kas Operasional', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 188, '2026-09-22T09:00:00+07:00'),
  ('1103', 'Bank BSI', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 512, '2026-09-22T09:00:00+07:00'),
  ('1104', 'Bank Mandiri', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 236, '2026-09-22T09:00:00+07:00'),
  ('1105', 'Bank BTN', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 74, '2026-09-18T09:00:00+07:00'),
  ('1106', 'Piutang Pasien', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 95, '2026-09-20T09:00:00+07:00'),
  ('1107', 'Persediaan Bahan Medis', 'Aset Lancar', '1000', '1100', '1100 - Persediaan', 'Debit', false, true, true, true, 162, '2026-09-21T09:00:00+07:00'),
  ('1108', 'Persediaan Obat', 'Aset Lancar', '1000', '1100', '1100 - Persediaan', 'Debit', false, true, true, true, 88, '2026-09-21T09:00:00+07:00'),
  ('1109', 'Persediaan Alat Habis Pakai', 'Aset Lancar', '1000', '1100', '1100 - Persediaan', 'Debit', false, true, true, true, 64, '2026-09-21T09:00:00+07:00'),
  ('1110', 'Persediaan Barang Dagang (Sikat Gigi, Mouthwash, dll)', 'Aset Lancar', '1000', '1100', '1100 - Persediaan', 'Debit', false, true, true, true, 47, '2026-09-19T09:00:00+07:00'),
  ('1112', 'Pajak Masukan', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 58, '2026-09-18T09:00:00+07:00'),
  ('1113', 'Biaya Dibayar Dimuka', 'Aset Lancar', '1000', '1100', '1100 - Aset Lancar', 'Debit', false, true, true, true, 22, '2026-09-10T09:00:00+07:00'),
  ('1201', 'Dental Unit', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 12, '2026-08-28T09:00:00+07:00'),
  ('1202', 'Autoclave', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 9, '2026-08-28T09:00:00+07:00'),
  ('1203', 'Dental X-Ray', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 7, '2026-08-28T09:00:00+07:00'),
  ('1204', 'Scaler Ultrasonic', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 11, '2026-08-28T09:00:00+07:00'),
  ('1205', 'Light Cure', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 14, '2026-08-28T09:00:00+07:00'),
  ('1206', 'Kompresor', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 8, '2026-08-28T09:00:00+07:00'),
  ('1207', 'Peralatan Medis Lainnya', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 6, '2026-08-28T09:00:00+07:00'),
  ('1211', 'Komputer', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 16, '2026-08-28T09:00:00+07:00'),
  ('1212', 'Printer', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 13, '2026-08-28T09:00:00+07:00'),
  ('1213', 'Meja & Kursi', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 10, '2026-08-28T09:00:00+07:00'),
  ('1214', 'AC', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 9, '2026-08-28T09:00:00+07:00'),
  ('1215', 'CCTV', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, false, false, 0, '2026-07-02T09:00:00+07:00'),
  ('1231', 'Renovasi Klinik', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 5, '2026-08-28T09:00:00+07:00'),
  ('1232', 'Interior Klinik', 'Aset Tetap', '1000', '1200', '1200 - Aset Tetap Berwujud', 'Debit', false, true, true, true, 4, '2026-08-28T09:00:00+07:00'),
  ('1291', 'Akumulasi Penyusutan Peralatan Medis', 'Aset Tetap', '1000', '1290', '1290 - Akumulasi Penyusutan', 'Kredit', false, true, true, true, 24, '2026-08-31T09:00:00+07:00'),
  ('1292', 'Akumulasi Penyusutan Peralatan Kantor', 'Aset Tetap', '1000', '1290', '1290 - Akumulasi Penyusutan', 'Kredit', false, true, true, true, 24, '2026-08-31T09:00:00+07:00'),
  ('1293', 'Akumulasi Penyusutan Kendaraan', 'Aset Tetap', '1000', '1290', '1290 - Akumulasi Penyusutan', 'Kredit', false, true, true, true, 18, '2026-08-31T09:00:00+07:00'),
  ('1294', 'Akumulasi Penyusutan Renovasi', 'Aset Tetap', '1000', '1290', '1290 - Akumulasi Penyusutan', 'Kredit', false, true, true, true, 14, '2026-08-31T09:00:00+07:00'),
  ('2000', 'LIABILITAS', 'Header Liabilitas', '2000', NULL, NULL, 'Kredit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('2101', 'Utang Usaha', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 196, '2026-09-21T09:00:00+07:00'),
  ('2102', 'Utang Pembelian Alat', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 41, '2026-09-17T09:00:00+07:00'),
  ('2103', 'Utang Gaji', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 52, '2026-09-05T09:00:00+07:00'),
  ('2104', 'Utang BPJS', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 36, '2026-09-10T09:00:00+07:00'),
  ('2105', 'Utang Pajak PPN', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 31, '2026-09-14T09:00:00+07:00'),
  ('2106', 'Utang PPh 21', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 44, '2026-09-10T09:00:00+07:00'),
  ('2107', 'Utang PPh 23', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 22, '2026-09-10T09:00:00+07:00'),
  ('2108', 'Utang PPh Badan', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 6, '2026-06-30T09:00:00+07:00'),
  ('2109', 'Pendapatan Diterima Dimuka', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 143, '2026-09-21T09:00:00+07:00'),
  ('2110', 'Biaya Masih Harus Dibayar', 'Liabilitas', '2000', '2100', '2100 - Liabilitas Lancar', 'Kredit', false, true, true, true, 28, '2026-09-19T09:00:00+07:00'),
  ('2201', 'Utang Bank', 'Liabilitas', '2000', '2200', '2200 - Liabilitas Jangka Panjang', 'Kredit', false, true, true, true, 24, '2026-09-01T09:00:00+07:00'),
  ('2202', 'Utang Leasing Alat', 'Liabilitas', '2000', '2200', '2200 - Liabilitas Jangka Panjang', 'Kredit', false, true, true, true, 12, '2026-09-01T09:00:00+07:00'),
  ('2203', 'Utang Leasing Kendaraan', 'Liabilitas', '2000', '2200', '2200 - Liabilitas Jangka Panjang', 'Kredit', false, true, true, true, 9, '2026-09-01T09:00:00+07:00'),
  ('3000', 'EKUITAS', 'Header Ekuitas', '3000', NULL, NULL, 'Kredit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('3101', 'Modal Pemilik', 'Ekuitas', '3000', '3100', '3100 - Modal & Saldo Laba', 'Kredit', false, true, true, true, 11, '2026-06-01T09:00:00+07:00'),
  ('3102', 'Prive', 'Ekuitas', '3000', '3100', '3100 - Modal & Saldo Laba', 'Debit', false, true, true, true, 8, '2026-08-12T09:00:00+07:00'),
  ('3103', 'Laba Ditahan', 'Ekuitas', '3000', '3100', '3100 - Modal & Saldo Laba', 'Kredit', false, true, true, true, 15, '2026-01-05T09:00:00+07:00'),
  ('3104', 'Laba Tahun Berjalan', 'Ekuitas', '3000', '3100', '3100 - Modal & Saldo Laba', 'Kredit', false, true, true, true, 2, '2026-09-01T09:00:00+07:00'),
  ('4000', 'PENDAPATAN', 'Header Pendapatan', '4000', NULL, NULL, 'Kredit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('4101', 'Pendapatan Jasa', 'Pendapatan Jasa', '4000', '4100', '4100 - Pendapatan Jasa', 'Kredit', false, true, true, true, 640, '2026-09-22T09:00:00+07:00'),
  ('4201', 'Penjualan Dental Kit', 'Pendapatan Penjualan', '4000', '4200', '4200 - Pendapatan Penjualan', 'Kredit', false, true, true, true, 96, '2026-09-20T09:00:00+07:00'),
  ('4202', 'Penjualan Produk Oral Care', 'Pendapatan Penjualan', '4000', '4200', '4200 - Pendapatan Penjualan', 'Kredit', false, true, true, true, 74, '2026-09-20T09:00:00+07:00'),
  ('4301', 'Pendapatan Administrasi', 'Pendapatan Lain-Lain', '4000', '4300', '4300 - Pendapatan Lain-Lain', 'Kredit', false, true, true, true, 35, '2026-09-15T09:00:00+07:00'),
  ('4302', 'Pendapatan Lain-lain', 'Pendapatan Lain-Lain', '4000', '4300', '4300 - Pendapatan Lain-Lain', 'Kredit', false, true, true, true, 12, '2026-09-02T09:00:00+07:00'),
  ('5000', 'HPP — HARGA POKOK PENJUALAN', 'Header HPP', '5000', NULL, NULL, 'Debit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('5101', 'Pemakaian Bahan Medis', 'HPP', '5000', '5100', '5100 - HPP Operasional Klinik', 'Debit', false, true, true, true, 288, '2026-09-22T09:00:00+07:00'),
  ('5102', 'Pemakaian Obat', 'HPP', '5000', '5100', '5100 - HPP Operasional Klinik', 'Debit', false, true, true, true, 121, '2026-09-21T09:00:00+07:00'),
  ('5103', 'Pemakaian Alat Habis Pakai', 'HPP', '5000', '5100', '5100 - HPP Operasional Klinik', 'Debit', false, true, true, true, 55, '2026-09-21T09:00:00+07:00'),
  ('5104', 'Harga Pokok Barang Dagang', 'HPP', '5000', '5100', '5100 - HPP Operasional Klinik', 'Debit', false, true, true, true, 49, '2026-09-18T09:00:00+07:00'),
  ('6000', 'BEBAN USAHA', 'Header Beban', '6000', NULL, NULL, 'Debit', true, false, true, true, 0, '2026-09-01T09:00:00+07:00'),
  ('6001', 'Jasa Medis Dokter', 'Biaya Langsung', '6000', '6000', '6000 - Biaya Langsung Layanan', 'Debit', false, true, true, true, 632, '2026-09-22T09:00:00+07:00'),
  ('6002', 'Pembelian Bahan Medis', 'Biaya Langsung', '6000', '6000', '6000 - Biaya Langsung Layanan', 'Debit', false, true, true, true, 154, '2026-09-20T09:00:00+07:00'),
  ('6003', 'Biaya Cetak Lab', 'Biaya Langsung', '6000', '6000', '6000 - Biaya Langsung Layanan', 'Debit', false, true, true, true, 88, '2026-09-19T09:00:00+07:00'),
  ('6004', 'Biaya Rontgen', 'Biaya Langsung', '6000', '6000', '6000 - Biaya Langsung Layanan', 'Debit', false, true, true, true, 96, '2026-09-19T09:00:00+07:00'),
  ('6102', 'Gaji Perawat', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 124, '2026-09-05T09:00:00+07:00'),
  ('6103', 'Gaji Admin', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 118, '2026-09-05T09:00:00+07:00'),
  ('6104', 'Insentif Dokter', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 96, '2026-09-10T09:00:00+07:00'),
  ('6105', 'Insentif Perawat', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 88, '2026-09-10T09:00:00+07:00'),
  ('6106', 'Bonus Karyawan', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 24, '2026-08-25T09:00:00+07:00'),
  ('6107', 'THR', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 12, '2026-04-20T09:00:00+07:00'),
  ('6108', 'BPJS Kesehatan', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 96, '2026-09-10T09:00:00+07:00'),
  ('6109', 'BPJS Ketenagakerjaan', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 96, '2026-09-10T09:00:00+07:00'),
  ('6110', 'Lembur', 'Biaya Gaji & SDM', '6000', '6100', '6100 - Biaya Gaji & SDM', 'Debit', false, true, true, true, 17, '2026-09-08T09:00:00+07:00'),
  ('6201', 'Listrik', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 98, '2026-09-07T09:00:00+07:00'),
  ('6202', 'Air', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 44, '2026-09-07T09:00:00+07:00'),
  ('6203', 'Internet', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 36, '2026-09-03T09:00:00+07:00'),
  ('6204', 'Telepon', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 18, '2026-09-03T09:00:00+07:00'),
  ('6205', 'Sewa Klinik', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 12, '2026-09-01T09:00:00+07:00'),
  ('6206', 'Keamanan', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 12, '2026-09-01T09:00:00+07:00'),
  ('6207', 'Kebersihan', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 24, '2026-09-04T09:00:00+07:00'),
  ('6208', 'Laundry', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 18, '2026-09-04T09:00:00+07:00'),
  ('6209', 'ATK', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 27, '2026-09-09T09:00:00+07:00'),
  ('6210', 'Bahan Kebersihan', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 19, '2026-09-09T09:00:00+07:00'),
  ('6211', 'Transportasi', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 22, '2026-09-13T09:00:00+07:00'),
  ('6212', 'BBM', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 31, '2026-09-13T09:00:00+07:00'),
  ('6213', 'Parkir', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 15, '2026-09-13T09:00:00+07:00'),
  ('6214', 'Konsumsi', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 33, '2026-09-12T09:00:00+07:00'),
  ('6215', 'Biaya Pengelolaan Limbah Medis', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 8, '2026-09-21T09:00:00+07:00'),
  ('6216', 'Pengiriman', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 14, '2026-09-16T09:00:00+07:00'),
  ('6217', 'Perlengkapan Klinik', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 9, '2026-09-16T09:00:00+07:00'),
  ('6218', 'Manajemen Fee', 'Biaya Oprasional', '6000', '6200', '6200 - Biaya Operasional', 'Debit', false, true, true, true, 12, '2026-09-22T09:00:00+07:00'),
  ('6301', 'Service Dental Unit', 'Biaya Pemeliharaan', '6000', '6300', '6300 - Biaya Pemeliharaan', 'Debit', false, true, true, true, 45, '2026-09-11T09:00:00+07:00'),
  ('6302', 'Kalibrasi Alat', 'Biaya Pemeliharaan', '6000', '6300', '6300 - Biaya Pemeliharaan', 'Debit', false, true, true, true, 11, '2026-08-29T09:00:00+07:00'),
  ('6303', 'Service AC', 'Biaya Pemeliharaan', '6000', '6300', '6300 - Biaya Pemeliharaan', 'Debit', false, true, true, true, 9, '2026-08-29T09:00:00+07:00'),
  ('6304', 'Perawatan Kendaraan', 'Biaya Pemeliharaan', '6000', '6300', '6300 - Biaya Pemeliharaan', 'Debit', false, true, true, true, 7, '2026-08-29T09:00:00+07:00'),
  ('6305', 'Perbaikan Gedung', 'Biaya Pemeliharaan', '6000', '6300', '6300 - Biaya Pemeliharaan', 'Debit', false, true, true, true, 5, '2026-08-29T09:00:00+07:00'),
  ('6401', 'Biaya Bank', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 96, '2026-09-22T09:00:00+07:00'),
  ('6402', 'Biaya Merchant QRIS', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 310, '2026-09-22T09:00:00+07:00'),
  ('6403', 'Biaya Software', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 44, '2026-09-03T09:00:00+07:00'),
  ('6404', 'Biaya Domain & Hosting', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 12, '2026-05-21T09:00:00+07:00'),
  ('6405', 'Biaya Perizinan', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 9, '2026-05-21T09:00:00+07:00'),
  ('6406', 'Biaya Pajak', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 15, '2026-09-12T09:00:00+07:00'),
  ('6407', 'Biaya Penyusutan', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 24, '2026-08-31T09:00:00+07:00'),
  ('6408', 'Biaya Amortisasi', 'Biaya Administrasi', '6000', '6400', '6400 - Biaya Administrasi', 'Debit', false, true, true, true, 6, '2026-08-31T09:00:00+07:00'),
  ('6501', 'Biaya Iklan Meta', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, true, true, 77, '2026-09-18T09:00:00+07:00'),
  ('6502', 'Biaya Google Ads', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, true, true, 45, '2026-09-18T09:00:00+07:00'),
  ('6503', 'Biaya Influencer', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, true, true, 19, '2026-08-30T09:00:00+07:00'),
  ('6504', 'Biaya Promosi', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, true, true, 22, '2026-09-10T09:00:00+07:00'),
  ('6505', 'Biaya Cetak Banner', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, true, true, 13, '2026-08-30T09:00:00+07:00'),
  ('6506', 'Biaya Event', 'Biaya Marketing', '6000', '6500', '6500 - Biaya Pemasaran', 'Debit', false, true, false, true, 6, '2026-06-11T09:00:00+07:00'),
  ('6601', 'Biaya Donasi', 'Biaya Lain-Lain', '6000', '6600', '6600 - Biaya di Luar Usaha', 'Debit', false, true, true, true, 18, '2026-09-02T09:00:00+07:00'),
  ('6602', 'Biaya Denda', 'Biaya Lain-Lain', '6000', '6600', '6600 - Biaya di Luar Usaha', 'Debit', false, true, true, true, 3, '2026-08-14T09:00:00+07:00'),
  ('6603', 'Biaya Lain-lain', 'Biaya Lain-Lain', '6000', '6600', '6600 - Biaya di Luar Usaha', 'Debit', false, true, true, true, 11, '2026-09-19T09:00:00+07:00')
on conflict (code) do update set
  name         = excluded.name,
  type_label   = excluded.type_label,
  group_code   = excluded.group_code,
  parent_code  = excluded.parent_code,
  parent_label = excluded.parent_label,
  normal       = excluded.normal,
  is_header    = excluded.is_header,
  can_post     = excluded.can_post,
  is_active    = excluded.is_active,
  is_locked    = excluded.is_locked,
  tx_count     = excluded.tx_count,
  updated_at   = excluded.updated_at;

-- ══════════════════════════════════════════════════════════════════
-- [3/6] SEED — finance_monthly + finance_overview_meta
-- source: supabase/seed_finance.sql
-- ══════════════════════════════════════════════════════════════════
-- AUTO-GENERATED by scripts/generate-finance-seed-sql.mjs — do not edit by hand.
-- Seeds the executive finance overview snapshots (9 months + 1 meta row).

insert into public.finance_monthly (id, month_label, month_label_long, revenue, hpp, opex, net_profit)
values
  ('2026-01', 'Jan', 'Januari 2026', 560000000, 128000000, 227000000, 205000000),
  ('2026-02', 'Feb', 'Februari 2026', 580000000, 133000000, 235000000, 212000000),
  ('2026-03', 'Mar', 'Maret 2026', 640000000, 149000000, 263000000, 228000000),
  ('2026-04', 'Apr', 'April 2026', 610000000, 141000000, 249000000, 220000000),
  ('2026-05', 'Mei', 'Mei 2026', 690000000, 158000000, 286000000, 246000000),
  ('2026-06', 'Jun', 'Juni 2026', 720000000, 166000000, 302000000, 252000000),
  ('2026-07', 'Jul', 'Juli 2026', 760000000, 176000000, 326000000, 258000000),
  ('2026-08', 'Ags', 'Agustus 2026', 738000000, 171000000, 318000000, 249000000),
  ('2026-09', 'Sep', 'September 2026', 842500000, 195400000, 382600000, 264500000)
on conflict (id) do update set
  month_label = excluded.month_label,
  month_label_long = excluded.month_label_long,
  revenue = excluded.revenue,
  hpp = excluded.hpp,
  opex = excluded.opex,
  net_profit = excluded.net_profit;

insert into public.finance_overview_meta (id, payload)
values (true, '{"periodLabel":"September 2026","periodStatus":"OPEN","revenueMix":{"jasaMedis":78,"produk":22},"grossMarginBenchmark":72,"netTargetDeltaPct":8.5,"autoSyncMinutes":2,"brands":[{"name":"Dentico Dental Care (A)","amount":480000000,"color":"primary"},{"name":"Dentico Smile Aesthetic (B)","amount":262500000,"color":"secondary"},{"name":"Dentico Kids Ortho (C)","amount":100000000,"color":"tertiary"}],"branches":[{"rank":1,"name":"Yogyakarta - Gejayan","amount":320000000},{"rank":2,"name":"Jakarta - Senopati","amount":310000000},{"rank":3,"name":"Surabaya - Gubeng","amount":212500000}],"branchCount":5,"topExpenses":[{"code":"6001","name":"Jasa Medis Dokter","amount":142000000},{"code":"6102","name":"Gaji Perawat","amount":88500000},{"code":"6501","name":"Biaya Iklan Meta","amount":34200000},{"code":"6201","name":"Listrik","amount":18400000},{"code":"6301","name":"Service Dental Unit","amount":12000000}],"pipeline":{"draftCount":2,"draftAmount":8650000,"reviewCount":1,"reviewAmount":12400000,"postedCount":318,"lockedPeriod":"Agustus 2026","reconMatchedPct":98.4,"reconDiffAmount":0,"reconPendingCount":2}}'::jsonb)
on conflict (id) do update set payload = excluded.payload;

-- ══════════════════════════════════════════════════════════════════
-- [4/6] SEED — journals + journal_lines
-- source: supabase/seed_journals.sql
-- ══════════════════════════════════════════════════════════════════
-- AUTO-GENERATED by scripts/generate-journal-seed-sql.mjs — do not edit by hand.
-- Seeds journals + journal_lines (8 journals, 16 lines).

insert into public.journals
  (number, date, journal_type, brand, branch, reference, description, total, status, operator_name, operator_role, operator_initials)
values
  ('JV/2026/09/0142', '2026-09-30', 'JP', 'Brand A', 'Yogyakarta - Gejayan', 'INV-8812', 'Penerimaan pembayaran tindakan bleaching & penambalan pasien drg. Anisa', 1500000, 'POSTED', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0141', '2026-09-30', 'JB', 'Brand B', 'Jakarta Selatan', 'PO-MED-441', 'Pembelian bahan medis & resin komposit dari vendor utama', 12400000, 'REVIEW', 'Dimas', 'Staff', 'DM'),
  ('JV/2026/09/0140', '2026-09-29', 'ADJ', 'Brand A', 'Yogyakarta - Gejayan', 'ADJ-USE-09', 'Penyesuaian pemakaian BMHP periode September berdasarkan stock opname', 4250000, 'POSTED', 'Nabila', 'Finance Lead', 'NB'),
  ('JV/2026/09/0139', '2026-09-29', 'JU', 'Brand A', 'Surabaya Timur', 'REK-09', 'Koreksi saldo kas kecil cabang Surabaya hasil rekonsiliasi internal', 850000, 'DRAFT', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0120', '2026-09-28', 'KK', 'Dentico Core', 'Consolidated HO', 'EXP-6201', 'Pembayaran tagihan listrik & utilitas 5 cabang periode September', 5000000, 'POSTED', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0118', '2026-09-27', 'KM', 'Brand A', 'Yogyakarta - Gejayan', 'DEP-2210', 'Uang muka pasien paket ortho 12 sesi atas nama Ratna P.', 6000000, 'POSTED', 'Sinta', 'Kasir', 'ST'),
  ('JV/2026/09/0136', '2026-09-29', 'JU', 'Dentico Core', 'Consolidated HO', 'PAY-MDR-09', 'Akrual biaya MDR QRIS minggu IV atas net settlement BSI', 2150000, 'APPROVED', 'Nabila', 'Finance Lead', 'NB'),
  ('JV/2026/09/0135', '2026-09-28', 'JB', 'Brand B', 'Jakarta Selatan', 'PO-LAB-118', 'Pembelian cetakan aligner lab dental pihak ketiga (draft input Dimas)', 7800000, 'DRAFT', 'Dimas', 'Staff', 'DM')
on conflict (number) do nothing;

insert into public.journal_lines
  (journal_id, line_no, account_code, account_name, memo, debit, credit)
values
  ((select id from public.journals where number = 'JV/2026/09/0142'), 1, '1103', 'Bank BSI', 'Penerimaan transfer QRIS pasien', 1500000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0142'), 2, '4101', 'Pendapatan Jasa', 'Pendapatan tindakan medis klinik', 0, 1500000),
  ((select id from public.journals where number = 'JV/2026/09/0141'), 1, '1107', 'Persediaan Bahan Medis', 'Restock BMHP bulan September', 12400000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0141'), 2, '2101', 'Utang Usaha', 'Termin 30 hari vendor', 0, 12400000),
  ((select id from public.journals where number = 'JV/2026/09/0140'), 1, '5101', 'Pemakaian Bahan Medis', 'Beban pemakaian bahan habis pakai', 4250000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0140'), 2, '1107', 'Persediaan Bahan Medis', 'Pengurangan persediaan hasil opname', 0, 4250000),
  ((select id from public.journals where number = 'JV/2026/09/0139'), 1, '1101', 'Kas Kecil', 'Penyesuaian saldo kas kecil', 850000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0139'), 2, '1104', 'Bank Mandiri', 'Transfer pengisian kas kecil', 0, 850000),
  ((select id from public.journals where number = 'JV/2026/09/0120'), 1, '6201', 'Listrik', 'Alokasi utilitas seluruh cabang', 5000000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0120'), 2, '1104', 'Bank Mandiri', 'Autodebet tagihan PLN & PDAM', 0, 5000000),
  ((select id from public.journals where number = 'JV/2026/09/0118'), 1, '1103', 'Bank BSI', 'Settlement QRIS dinamis kasir pasien', 6000000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0118'), 2, '2109', 'Pendapatan Diterima Dimuka', 'Deposit paket ortho 12 sesi', 0, 6000000),
  ((select id from public.journals where number = 'JV/2026/09/0136'), 1, '6402', 'Biaya Merchant QRIS', 'MDR 0.7% gross QRIS minggu IV', 2150000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0136'), 2, '1103', 'Bank BSI', 'Net-off settlement BSI', 0, 2150000),
  ((select id from public.journals where number = 'JV/2026/09/0135'), 1, '6003', 'Biaya Cetak Lab', 'Cetakan aligner 26 unit', 7800000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0135'), 2, '2101', 'Utang Usaha', 'Invoice lab termin 14 hari', 0, 7800000)
on conflict (journal_id, line_no) do update set
  account_code = excluded.account_code,
  account_name = excluded.account_name,
  memo         = excluded.memo,
  debit        = excluded.debit,
  credit       = excluded.credit;

-- ══════════════════════════════════════════════════════════════════
-- [5/6] SEED — gl_supplements
-- source: supabase/seed_ledger.sql
-- ══════════════════════════════════════════════════════════════════
-- AUTO-GENERATED by scripts/generate-ledger-seed-sql.mjs — do not edit by hand.
-- Integrity-verified GL supplement postings (23 rows).

insert into public.gl_supplements
  (ref_id, account_code, date, time, voucher, ref, branch, dot, description, sub_desc, offset_label, debit, credit, bukti, memo)
values
  ('s-1103-01', '1103', '2026-09-02', '14:15', 'JV-2026/09/0014', 'POS-GJY-2026-0902-004', 'Brand A - Gejayan', 'primary', 'Setoran Penerimaan Kasir Pasien Tindakan drg. Anisa', 'Pasien #PT-2940 An. Shafa Almira (Scaling + Bleaching)', '[4101] Pendapatan Jasa', 34500000, 0, 'receipt', 'Setoran harian kasir front desk atas tindakan scaling, bleaching, dan tumpat komposit pasien Shafa Almira. Pembayaran via debit BCA dan tunai.'),
  ('s-1103-02', '1103', '2026-09-05', '11:30', 'CD-0105', 'PO-MAT-2026-0881', 'Dentico Group (HO)', 'tertiary', 'Pembayaran Bahan Medis Komposit & Bonding Dental Supply', 'Faktur Pajak FP-010-99238 • PT Cobra Dental Indonesia', '[2101] Utang Usaha', 0, 68200000, 'attach', 'Pelunasan termin pertama pembelian resin komposit nanofiller dan bonding agent untuk 3 cabang. Transfer BSI verified.'),
  ('s-1103-03', '1103', '2026-09-12', '09:05', 'CR-0082', 'STL-MDR-99021', 'Brand A - Gejayan', 'primary', 'Settlement Kliring EDC Merchant & QRIS Midtrans', 'Auto-Reconciled Batch #881902 • 142 Pasien Terlayani', '[4101] Pendapatan Jasa', 158400000, 0, 'verified', 'Settlement kliring EDC Bank Mandiri & QRIS Midtrans atas 38 pasien klinik cabang Gejayan. Biaya MDR merchant dipotong langsung dari akun penampung operasional.'),
  ('s-1103-04', '1103', '2026-09-15', '16:20', 'CD-0120', 'TRF-BSI-7740', 'Brand A - Gejayan', 'primary', 'Pengisian Kembali (Top-Up) Kas Kecil Front Desk', 'Reimbursement Operasional Periode September Tahap I', '[1101] Kas Kecil', 0, 15000000, 'receipt', 'Top-up imprest petty cash laci kasir front desk klinik Gejayan sesuai batas maksimum Rp 30.000.000.'),
  ('s-1103-05', '1103', '2026-09-18', '17:00', 'JV-2026/09/0142', 'POS-GJY-2026-0918-091', 'Brand A - Gejayan', 'primary', 'Penerimaan Kasir Paket Ortodonti & Bedah Mulut (Odontektomi)', 'drg. Bayu Pratama, Sp.BM & drg. Cindy, Sp.Ort (18 Pasien)', '[4101] Pendapatan Jasa', 210500000, 0, 'receipt', 'Penerimaan paket behel metal 12 bulan dan tindakan odontektomi gigi bungsu atas 18 pasien. Termin kedua diterima penuh via transfer dan QRIS.'),
  ('s-1103-06', '1103', '2026-09-20', '13:45', 'CD-0145', 'JM-DISB-202609', 'Brand A - Gejayan', 'primary', 'Disbursement Jasa Medis Dokter Gigi (Periode 1-15 Sep)', 'Payroll Transfer BSI Bulk • 9 Dokter Gigi Umum & Spesialis', '[6001] Jasa Medis Dokter', 0, 188650000, 'verified', 'Pembayaran jasa medis honor dokter gigi periode pertama September sesuai rekapitulasi fee tindakan 40% dari pendapatan jasa medis cabang.'),
  ('s-1103-07', '1103', '2026-09-24', '10:10', 'CD-0160', 'PLN-0924-88', 'Brand A - Gejayan', 'primary', 'Pembayaran Tagihan Listrik PLN 33kVA & Limbah Medis B3', 'Autodebit BSI Rekening Klinik • IDPEL: 5382-9901-2291', '[6201] Listrik', 0, 18000000, 'receipt', 'Autodebit tagihan listrik klinik Gejayan dan retribusi pengelolaan limbah medis B3 pihak ketiga berizin KLHK.'),
  ('s-1103-08', '1103', '2026-09-30', '19:30', 'CR-0112', 'INS-CLM-202609', 'Brand A - Gejayan', 'primary', 'Pencairan Klaim Asuransi Korporat & Pasien VIP Akhir Bulan', 'Admedika, Halodoc Dental, Mandiri Inhealth (34 Klaim Disetujui)', '[1106] Piutang Pasien', 238900000, 0, 'verified', 'Pencairan klaim asuransi korporat batch September: 34 klaim disetujui penuh tanpa potongan administrasi excess.'),
  ('s-1103-09', '1103', '2026-09-30', '23:59', 'CD-0199', 'BSI-FEE-SEP26', 'Dentico Group (HO)', 'tertiary', 'Beban Pemeliharaan Server Cloud Klinik & Administrasi Giro BSI', 'Autodebit Rekening Giro & Potongan Pajak Bunga Deposito', '[6401] Biaya Bank', 0, 132000000, 'doc', 'Administrasi bulanan rekening giro, fee RTGS/kliring, langganan server cloud EMR klinik, dan potongan pajak final bunga deposito.'),
  ('s-1101-01', '1101', '2026-09-03', '09:10', 'CR-0011', 'POS-GJY-0903-011', 'Brand A - Gejayan', 'primary', 'Penerimaan Tunai Kasir Walk-In Pagi', '4 pasien kontrol & pembersihan karang gigi', '[4101] Pendapatan Jasa', 4000000, 0, 'receipt', NULL),
  ('s-1101-02', '1101', '2026-09-09', '15:40', 'CD-0092', 'ATK-2026-3301', 'Brand A - Gejayan', 'primary', 'Pembelian ATK & Perlengkapan Front Desk', 'Kertas struk thermal, map rekam medis, tinta label', '[6209] ATK', 0, 1750000, 'receipt', NULL),
  ('s-1101-03', '1101', '2026-09-15', '16:20', 'CD-0120', 'TRF-BSI-7740', 'Brand A - Gejayan', 'primary', 'Top-Up Imprest Kas Kecil dari Bank BSI', 'Pengisian kembali batas imprest front desk', '[1103] Bank BSI', 15000000, 0, 'verified', NULL),
  ('s-1101-04', '1101', '2026-09-22', '11:05', 'CD-0129', 'RMB-TRN-2210', 'Brand A - Gejayan', 'primary', 'Reimburse Transport & Konsumsi Rapat Internal', 'Parking pass & konsumsi briefing tim shift', '[6211] Transportasi', 0, 3100000, 'receipt', NULL),
  ('s-4101-01', '4101', '2026-09-02', '14:15', 'JV-2026/09/0014', 'POS-GJY-2026-0902-004', 'Brand A - Gejayan', 'primary', 'Pendapatan Tindakan Scaling & Bleaching drg. Anisa', 'Pasien #PT-2940 An. Shafa Almira', '[1103] Bank BSI', 0, 34500000, 'receipt', NULL),
  ('s-4101-02', '4101', '2026-09-07', '16:45', 'JV-2026/09/0067', 'POS-SNP-0907-118', 'Brand B - Senopati', 'primary', 'Pendapatan Veneer & Estetik Senyum (4 Pasien)', 'drg. Laras Maheswari — veneer porcelain E-max', '[1103] Bank BSI', 0, 56200000, 'verified', NULL),
  ('s-4101-03', '4101', '2026-09-18', '17:00', 'JV-2026/09/0142', 'POS-GJY-2026-0918-091', 'Brand A - Gejayan', 'primary', 'Pendapatan Paket Ortodonti & Odontektomi', 'drg. Bayu Pratama, Sp.BM & drg. Cindy, Sp.Ort (18 Pasien)', '[1103] Bank BSI', 0, 210500000, 'receipt', NULL),
  ('s-4101-04', '4101', '2026-09-25', '15:20', 'JV-2026/09/0155', 'POS-GBG-0925-077', 'Brand A - Gubeng', 'primary', 'Pendapatan Cabut Gigi & Pemeriksaan Rutin Surabaya', '26 pasien periode 21-25 September', '[1104] Bank Mandiri', 0, 102600000, 'verified', NULL),
  ('s-5101-01', '5101', '2026-09-08', '10:25', 'JE-ADJ-0902', 'USE-BMHP-0902', 'Brand A - Gejayan', 'primary', 'Pemakaian Anestesi & Komposit Minggu I', 'Stock opname rolling — unit 1 & 2', '[1107] Persediaan Bahan Medis', 3850000, 0, 'doc', NULL),
  ('s-5101-02', '5101', '2026-09-18', '12:10', 'JE-ADJ-0915', 'USE-BMHP-0915', 'Brand A - Gejayan', 'primary', 'Pemakaian Bahan Cetak & Gypsum Ortho', 'Alginate, dental stone, kawat niti', '[1107] Persediaan Bahan Medis', 2975000, 0, 'doc', NULL),
  ('s-6001-01', '6001', '2026-09-13', '14:00', 'CD-0119', 'JM-ROLL-0913', 'Brand A - Gejayan', 'primary', 'Jasa Medis Dokter Gigi Periode 01-12 September', 'Rekap fee tindakan 40% • rolling payment', '[1103] Bank BSI', 142000000, 0, 'verified', NULL),
  ('s-6001-02', '6001', '2026-09-20', '13:45', 'CD-0145', 'JM-DISB-202609', 'Brand A - Gejayan', 'primary', 'Sisa Disbursement JM Dokter (Spesialis)', 'Payroll transfer BSI bulk lanjutan', '[1103] Bank BSI', 46650000, 0, 'verified', NULL),
  ('s-6201-01', '6201', '2026-09-10', '08:55', 'CD-0098', 'PLN-0910-41', 'Brand B - Senopati', 'primary', 'Tagihan Listrik PLN 16.5kVA Cabang Senopati', 'IDPEL 5120-8831-7745 • autodebit Mandiri', '[1104] Bank Mandiri', 8400000, 0, 'receipt', NULL),
  ('s-6201-02', '6201', '2026-09-21', '10:40', 'CD-0148', 'B3-KLHK-0921', 'Brand A - Gejayan', 'primary', 'Retribusi Pengelolaan Limbah Medis B3', 'Vendor berizin KLHK — manifest elektronik', '[1103] Bank BSI', 2050000, 0, 'doc', NULL)
on conflict (ref_id) do nothing;

-- ══════════════════════════════════════════════════════════════════
-- [6/6] SEED — pnl_account_postings
-- source: supabase/seed_pnl.sql
-- ══════════════════════════════════════════════════════════════════
-- AUTO-GENERATED by scripts/generate-pnl-seed-sql.mjs — do not edit by hand.
-- Aggregated P&L postings: 58 accounts × 3 periods.

insert into public.pnl_account_postings (seq, code, period, amount, tag)
values
  (undefined, '4101', '2026-09', 680000000, NULL),
  (undefined, '4101', '2026-08', 595000000, NULL),
  (undefined, '4101', '2026-07', 613000000, NULL),
  (undefined, '4201', '2026-09', 48000000, NULL),
  (undefined, '4201', '2026-08', 42000000, NULL),
  (undefined, '4201', '2026-07', 44000000, NULL),
  (undefined, '4202', '2026-09', 43500000, NULL),
  (undefined, '4202', '2026-08', 38000000, NULL),
  (undefined, '4202', '2026-07', 39000000, NULL),
  (undefined, '4301', '2026-09', 64000000, NULL),
  (undefined, '4301', '2026-08', 56000000, NULL),
  (undefined, '4301', '2026-07', 58000000, NULL),
  (undefined, '6001', '2026-09', 142000000, NULL),
  (undefined, '6001', '2026-08', 124000000, NULL),
  (undefined, '6001', '2026-07', 128000000, NULL),
  (undefined, '6002', '2026-09', 38000000, NULL),
  (undefined, '6002', '2026-08', 33000000, NULL),
  (undefined, '6002', '2026-07', 34000000, NULL),
  (undefined, '6003', '2026-09', 12500000, NULL),
  (undefined, '6003', '2026-08', 11000000, NULL),
  (undefined, '6003', '2026-07', 11000000, NULL),
  (undefined, '6004', '2026-09', 4500000, NULL),
  (undefined, '6004', '2026-08', 4000000, NULL),
  (undefined, '6004', '2026-07', 4000000, NULL),
  (undefined, '6102', '2026-09', 38000000, NULL),
  (undefined, '6102', '2026-08', 33000000, NULL),
  (undefined, '6102', '2026-07', 34000000, NULL),
  (undefined, '6103', '2026-09', 24000000, NULL),
  (undefined, '6103', '2026-08', 21000000, NULL),
  (undefined, '6103', '2026-07', 22000000, NULL),
  (undefined, '6104', '2026-09', 28000000, NULL),
  (undefined, '6104', '2026-08', 24000000, NULL),
  (undefined, '6104', '2026-07', 25000000, NULL),
  (undefined, '6105', '2026-09', 12000000, NULL),
  (undefined, '6105', '2026-08', 10000000, NULL),
  (undefined, '6105', '2026-07', 10500000, NULL),
  (undefined, '6106', '2026-09', 8000000, NULL),
  (undefined, '6106', '2026-08', 7000000, NULL),
  (undefined, '6106', '2026-07', 7000000, NULL),
  (undefined, '6107', '2026-09', 0, NULL),
  (undefined, '6107', '2026-08', 0, NULL),
  (undefined, '6107', '2026-07', 0, NULL),
  (undefined, '6108', '2026-09', 9500000, NULL),
  (undefined, '6108', '2026-08', 8300000, NULL),
  (undefined, '6108', '2026-07', 8500000, NULL),
  (undefined, '6109', '2026-09', 8500000, NULL),
  (undefined, '6109', '2026-08', 7400000, NULL),
  (undefined, '6109', '2026-07', 7600000, NULL),
  (undefined, '6110', '2026-09', 10000000, NULL),
  (undefined, '6110', '2026-08', 8300000, NULL),
  (undefined, '6110', '2026-07', 8400000, NULL),
  (undefined, '6201', '2026-09', 12000000, NULL),
  (undefined, '6201', '2026-08', 10500000, NULL),
  (undefined, '6201', '2026-07', 10800000, NULL),
  (undefined, '6202', '2026-09', 3200000, NULL),
  (undefined, '6202', '2026-08', 2800000, NULL),
  (undefined, '6202', '2026-07', 2900000, NULL),
  (undefined, '6203', '2026-09', 4500000, NULL),
  (undefined, '6203', '2026-08', 3900000, NULL),
  (undefined, '6203', '2026-07', 4000000, NULL),
  (undefined, '6204', '2026-09', 1500000, NULL),
  (undefined, '6204', '2026-08', 1300000, NULL),
  (undefined, '6204', '2026-07', 1400000, NULL),
  (undefined, '6205', '2026-09', 35000000, NULL),
  (undefined, '6205', '2026-08', 30000000, NULL),
  (undefined, '6205', '2026-07', 31000000, NULL),
  (undefined, '6206', '2026-09', 6000000, NULL),
  (undefined, '6206', '2026-08', 5200000, NULL),
  (undefined, '6206', '2026-07', 5400000, NULL),
  (undefined, '6207', '2026-09', 7500000, NULL),
  (undefined, '6207', '2026-08', 6500000, NULL),
  (undefined, '6207', '2026-07', 6700000, NULL),
  (undefined, '6208', '2026-09', 3200000, NULL),
  (undefined, '6208', '2026-08', 2800000, NULL),
  (undefined, '6208', '2026-07', 2900000, NULL),
  (undefined, '6209', '2026-09', 2800000, NULL),
  (undefined, '6209', '2026-08', 2400000, NULL),
  (undefined, '6209', '2026-07', 2500000, NULL),
  (undefined, '6210', '2026-09', 2400000, NULL),
  (undefined, '6210', '2026-08', 2100000, NULL),
  (undefined, '6210', '2026-07', 2200000, NULL),
  (undefined, '6211', '2026-09', 3800000, NULL),
  (undefined, '6211', '2026-08', 3300000, NULL),
  (undefined, '6211', '2026-07', 3400000, NULL),
  (undefined, '6212', '2026-09', 4500000, NULL),
  (undefined, '6212', '2026-08', 3900000, NULL),
  (undefined, '6212', '2026-07', 4000000, NULL),
  (undefined, '6213', '2026-09', 1200000, NULL),
  (undefined, '6213', '2026-08', 1000000, NULL),
  (undefined, '6213', '2026-07', 1100000, NULL),
  (undefined, '6214', '2026-09', 5600000, NULL),
  (undefined, '6214', '2026-08', 4900000, NULL),
  (undefined, '6214', '2026-07', 5000000, NULL),
  (undefined, '6215', '2026-09', 4500000, NULL),
  (undefined, '6215', '2026-08', 3900000, NULL),
  (undefined, '6215', '2026-07', 4000000, NULL),
  (undefined, '6216', '2026-09', 1800000, NULL),
  (undefined, '6216', '2026-08', 1500000, NULL),
  (undefined, '6216', '2026-07', 1600000, NULL),
  (undefined, '6217', '2026-09', 1700000, NULL),
  (undefined, '6217', '2026-08', 1200000, NULL),
  (undefined, '6217', '2026-07', 1200000, NULL),
  (undefined, '6218', '2026-09', 2000000, NULL),
  (undefined, '6218', '2026-08', 1800000, NULL),
  (undefined, '6218', '2026-07', 1900000, NULL),
  (undefined, '6301', '2026-09', 11000000, NULL),
  (undefined, '6301', '2026-08', 9500000, NULL),
  (undefined, '6301', '2026-07', 9800000, NULL),
  (undefined, '6302', '2026-09', 4500000, NULL),
  (undefined, '6302', '2026-08', 3900000, NULL),
  (undefined, '6302', '2026-07', 4000000, NULL),
  (undefined, '6303', '2026-09', 5000000, NULL),
  (undefined, '6303', '2026-08', 4300000, NULL),
  (undefined, '6303', '2026-07', 4500000, NULL),
  (undefined, '6304', '2026-09', 4500000, NULL),
  (undefined, '6304', '2026-08', 3900000, NULL),
  (undefined, '6304', '2026-07', 4000000, NULL),
  (undefined, '6305', '2026-09', 3500000, NULL),
  (undefined, '6305', '2026-08', 3000000, NULL),
  (undefined, '6305', '2026-07', 3100000, NULL),
  (undefined, '6401', '2026-09', 3800000, NULL),
  (undefined, '6401', '2026-08', 3300000, NULL),
  (undefined, '6401', '2026-07', 3400000, NULL),
  (undefined, '6402', '2026-09', 8400000, NULL),
  (undefined, '6402', '2026-08', 7300000, NULL),
  (undefined, '6402', '2026-07', 7500000, NULL),
  (undefined, '6403', '2026-09', 5500000, NULL),
  (undefined, '6403', '2026-08', 4800000, NULL),
  (undefined, '6403', '2026-07', 4900000, NULL),
  (undefined, '6404', '2026-09', 1200000, NULL),
  (undefined, '6404', '2026-08', 1000000, NULL),
  (undefined, '6404', '2026-07', 1100000, NULL),
  (undefined, '6405', '2026-09', 2500000, NULL),
  (undefined, '6405', '2026-08', 2200000, NULL),
  (undefined, '6405', '2026-07', 2200000, NULL),
  (undefined, '6406', '2026-09', 8100000, NULL),
  (undefined, '6406', '2026-08', 7000000, NULL),
  (undefined, '6406', '2026-07', 7200000, NULL),
  (undefined, '6407', '2026-09', 18000000, NULL),
  (undefined, '6407', '2026-08', 15700000, NULL),
  (undefined, '6407', '2026-07', 16000000, NULL),
  (undefined, '6408', '2026-09', 6000000, NULL),
  (undefined, '6408', '2026-08', 5200000, NULL),
  (undefined, '6408', '2026-07', 5300000, NULL),
  (undefined, '6501', '2026-09', 18000000, NULL),
  (undefined, '6501', '2026-08', 16000000, NULL),
  (undefined, '6501', '2026-07', 14500000, NULL),
  (undefined, '6502', '2026-09', 12000000, NULL),
  (undefined, '6502', '2026-08', 10500000, NULL),
  (undefined, '6502', '2026-07', 9500000, NULL),
  (undefined, '6503', '2026-09', 8500000, NULL),
  (undefined, '6503', '2026-08', 7000000, NULL),
  (undefined, '6503', '2026-07', 5800000, NULL),
  (undefined, '6504', '2026-09', 6500000, NULL),
  (undefined, '6504', '2026-08', 5000000, NULL),
  (undefined, '6504', '2026-07', 4500000, NULL),
  (undefined, '6505', '2026-09', 4000000, NULL),
  (undefined, '6505', '2026-08', 3500000, NULL),
  (undefined, '6505', '2026-07', 3200000, NULL),
  (undefined, '6506', '2026-09', 6000000, NULL),
  (undefined, '6506', '2026-08', 0, NULL),
  (undefined, '6506', '2026-07', 3000000, NULL),
  (undefined, '4302', '2026-09', 7000000, NULL),
  (undefined, '4302', '2026-08', 6100000, NULL),
  (undefined, '4302', '2026-07', 6500000, NULL),
  (undefined, '6601', '2026-09', 1200000, NULL),
  (undefined, '6601', '2026-08', 900000, NULL),
  (undefined, '6601', '2026-07', 950000, NULL),
  (undefined, '6602', '2026-09', 300000, NULL),
  (undefined, '6602', '2026-08', 200000, NULL),
  (undefined, '6602', '2026-07', 250000, NULL),
  (undefined, '6603', '2026-09', 800000, NULL),
  (undefined, '6603', '2026-08', 600000, NULL),
  (undefined, '6603', '2026-07', 650000, NULL)
on conflict (code, period) do update set
  seq    = excluded.seq,
  amount = excluded.amount,
  tag    = excluded.tag;

-- ═══════════════════════════════════════════════════════════════════
-- VERIFICATION — every row count must be greater than zero.
-- ═══════════════════════════════════════════════════════════════════
select 'coa_accounts'            as object, count(*) as rows from public.coa_accounts
union all select 'finance_monthly',        count(*) from public.finance_monthly
union all select 'finance_overview_meta',  count(*) from public.finance_overview_meta
union all select 'journals',               count(*) from public.journals
union all select 'journal_lines',          count(*) from public.journal_lines
union all select 'gl_supplements',         count(*) from public.gl_supplements
union all select 'pnl_account_postings',   count(*) from public.pnl_account_postings
union all select 'gl_account_movements',   count(*) from public.gl_account_movements
order by 1;
