-- AUTO-GENERATED by scripts/generate-journal-seed-sql.mjs — do not edit by hand.
-- Seeds journals + journal_lines (8 journals, 16 lines).

insert into public.journals
  (number, date, journal_type, brand, branch, reference, description, total, status, operator_name, operator_role, operator_initials)
values
  ('JV/2026/09/0142', '2026-09-30', 'JP', 'Brand A', 'Yogyakarta - Gejayan', 'INV-8812', 'Penerimaan pembayaran tindakan bleaching & penambalan pasien drg. Anisa', 1500000, 'POSTED', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0141', '2026-09-30', 'JB', 'Brand B', 'Jakarta Selatan', 'PO-MED-441', 'Pembelian bahan medis & resin komposit dari vendor utama', 12400000, 'REVIEW', 'Dimas', 'Staff', 'DM'),
  ('JV/2026/09/0140', '2026-09-29', 'ADJ', 'Brand A', 'Yogyakarta - Gejayan', 'ADJ-USE-09', 'Penyesuaian pemakaian BMHP periode September berdasarkan stock opname', 4250000, 'POSTED', 'Nabila', 'Finance Lead', 'NB'),
  ('JV/2026/09/0139', '2026-09-29', 'JU', 'Brand A', 'Surabaya Timur', 'REK-09', 'Koreksi saldo kas kecil cabang Surabaya hasil rekonsiliasi internal', 850000, 'DRAFT', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0120', '2026-09-28', 'KK', 'Dentico Core', 'Consolidated HO', 'EXP-6201', 'Pembayaran tagihan listrik & utilitas 5 cabang periode September', 5000000, 'POSTED', 'Falah', 'Staff', 'FL'),
  ('JV/2026/09/0118', '2026-09-27', 'KM', 'Brand A', 'Yogyakarta - Gejayan', 'DEP-2210', 'Uang muka pasien paket ortho 12 sesi atas nama Ratna P.', 6000000, 'POSTED', 'Sinta', 'Kasir', 'ST'),
  ('JV/2026/09/0136', '2026-09-29', 'JU', 'Dentico Core', 'Consolidated HO', 'PAY-MDR-09', 'Akrual biaya MDR QRIS minggu IV atas net settlement BSI', 2150000, 'APPROVED', 'Nabila', 'Finance Lead', 'NB'),
  ('JV/2026/09/0135', '2026-09-28', 'JB', 'Brand B', 'Jakarta Selatan', 'PO-LAB-118', 'Pembelian cetakan aligner lab dental pihak ketiga (draft input Dimas)', 7800000, 'DRAFT', 'Dimas', 'Staff', 'DM')
on conflict (number) do nothing;

insert into public.journal_lines
  (journal_id, line_no, account_code, account_name, memo, debit, credit)
values
  ((select id from public.journals where number = 'JV/2026/09/0142'), 1, '1103', 'Bank BSI', 'Penerimaan transfer QRIS pasien', 1500000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0142'), 2, '4101', 'Pendapatan Jasa', 'Pendapatan tindakan medis klinik', 0, 1500000),
  ((select id from public.journals where number = 'JV/2026/09/0141'), 1, '1107', 'Persediaan Bahan Medis', 'Restock BMHP bulan September', 12400000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0141'), 2, '2101', 'Utang Usaha', 'Termin 30 hari vendor', 0, 12400000),
  ((select id from public.journals where number = 'JV/2026/09/0140'), 1, '5101', 'Pemakaian Bahan Medis', 'Beban pemakaian bahan habis pakai', 4250000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0140'), 2, '1107', 'Persediaan Bahan Medis', 'Pengurangan persediaan hasil opname', 0, 4250000),
  ((select id from public.journals where number = 'JV/2026/09/0139'), 1, '1101', 'Kas Kecil', 'Penyesuaian saldo kas kecil', 850000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0139'), 2, '1104', 'Bank Mandiri', 'Transfer pengisian kas kecil', 0, 850000),
  ((select id from public.journals where number = 'JV/2026/09/0120'), 1, '6201', 'Listrik', 'Alokasi utilitas seluruh cabang', 5000000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0120'), 2, '1104', 'Bank Mandiri', 'Autodebet tagihan PLN & PDAM', 0, 5000000),
  ((select id from public.journals where number = 'JV/2026/09/0118'), 1, '1103', 'Bank BSI', 'Settlement QRIS dinamis kasir pasien', 6000000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0118'), 2, '2109', 'Pendapatan Diterima Dimuka', 'Deposit paket ortho 12 sesi', 0, 6000000),
  ((select id from public.journals where number = 'JV/2026/09/0136'), 1, '6402', 'Biaya Merchant QRIS', 'MDR 0.7% gross QRIS minggu IV', 2150000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0136'), 2, '1103', 'Bank BSI', 'Net-off settlement BSI', 0, 2150000),
  ((select id from public.journals where number = 'JV/2026/09/0135'), 1, '6003', 'Biaya Cetak Lab', 'Cetakan aligner 26 unit', 7800000, 0),
  ((select id from public.journals where number = 'JV/2026/09/0135'), 2, '2101', 'Utang Usaha', 'Invoice lab termin 14 hari', 0, 7800000)
on conflict (journal_id, line_no) do update set
  account_code = excluded.account_code,
  account_name = excluded.account_name,
  memo         = excluded.memo,
  debit        = excluded.debit,
  credit       = excluded.credit;
