-- AUTO-GENERATED by scripts/generate-finance-seed-sql.mjs — do not edit by hand.
-- Seeds the executive finance overview snapshots (9 months + 1 meta row).

insert into public.finance_monthly (id, month_label, month_label_long, revenue, hpp, opex, net_profit)
values
  ('2026-01', 'Jan', 'Januari 2026', 560000000, 128000000, 227000000, 205000000),
  ('2026-02', 'Feb', 'Februari 2026', 580000000, 133000000, 235000000, 212000000),
  ('2026-03', 'Mar', 'Maret 2026', 640000000, 149000000, 263000000, 228000000),
  ('2026-04', 'Apr', 'April 2026', 610000000, 141000000, 249000000, 220000000),
  ('2026-05', 'Mei', 'Mei 2026', 690000000, 158000000, 286000000, 246000000),
  ('2026-06', 'Jun', 'Juni 2026', 720000000, 166000000, 302000000, 252000000),
  ('2026-07', 'Jul', 'Juli 2026', 760000000, 176000000, 326000000, 258000000),
  ('2026-08', 'Ags', 'Agustus 2026', 738000000, 171000000, 318000000, 249000000),
  ('2026-09', 'Sep', 'September 2026', 842500000, 195400000, 382600000, 264500000)
on conflict (id) do update set
  month_label = excluded.month_label,
  month_label_long = excluded.month_label_long,
  revenue = excluded.revenue,
  hpp = excluded.hpp,
  opex = excluded.opex,
  net_profit = excluded.net_profit;

insert into public.finance_overview_meta (id, payload)
values (true, '{"periodLabel":"September 2026","periodStatus":"OPEN","revenueMix":{"jasaMedis":78,"produk":22},"grossMarginBenchmark":72,"netTargetDeltaPct":8.5,"autoSyncMinutes":2,"brands":[{"name":"Dentico Dental Care (A)","amount":480000000,"color":"primary"},{"name":"Dentico Smile Aesthetic (B)","amount":262500000,"color":"secondary"},{"name":"Dentico Kids Ortho (C)","amount":100000000,"color":"tertiary"}],"branches":[{"rank":1,"name":"Yogyakarta - Gejayan","amount":320000000},{"rank":2,"name":"Jakarta - Senopati","amount":310000000},{"rank":3,"name":"Surabaya - Gubeng","amount":212500000}],"branchCount":5,"topExpenses":[{"code":"6001","name":"Jasa Medis Dokter","amount":142000000},{"code":"6102","name":"Gaji Perawat","amount":88500000},{"code":"6501","name":"Biaya Iklan Meta","amount":34200000},{"code":"6201","name":"Listrik","amount":18400000},{"code":"6301","name":"Service Dental Unit","amount":12000000}],"pipeline":{"draftCount":2,"draftAmount":8650000,"reviewCount":1,"reviewAmount":12400000,"postedCount":318,"lockedPeriod":"Agustus 2026","reconMatchedPct":98.4,"reconDiffAmount":0,"reconPendingCount":2}}'::jsonb)
on conflict (id) do update set payload = excluded.payload;
