import { supabase, isSupabaseEnabled } from "../lib/supabase";
import { GL_SUPPLEMENTS, type GlSupplement } from "./ledger";

/* ────────────────────────────────────────────────────────────────────
 * GL Supplement Repository — supplements model integrity-verified
 * postings generated by upstream engines (POS batch, payroll bulk,
 * QRIS clearing) that pre-date the interactive journal registry.
 * In Supabase mode they live in the `gl_supplements` table.
 * ──────────────────────────────────────────────────────────────────── */

const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));

// eslint-disable-next-line @typescript-eslint/no-explicit-any
function fromRow(r: any): GlSupplement {
  return {
    id: r.ref_id ?? r.id,
    accountCode: r.account_code,
    date: r.date,
    time: r.time,
    voucher: r.voucher,
    ref: r.ref ?? "",
    branch: r.branch,
    dot: r.dot ?? "primary",
    description: r.description,
    subDescription: r.sub_desc ?? undefined,
    offsetLabel: r.offset_label,
    debit: Number(r.debit),
    credit: Number(r.credit),
    bukti: r.bukti ?? "receipt",
    memo: r.memo ?? undefined,
  };
}

export async function fetchGlSupplements(): Promise<{ data: GlSupplement[]; source: "supabase" | "demo" }> {
  if (isSupabaseEnabled && supabase) {
    try {
      const { data, error } = await supabase.from("gl_supplements").select("*");
      if (!error && data && data.length > 0) {
        return { data: data.map(fromRow), source: "supabase" };
      }
      console.warn("[gl] Supplements table empty/unavailable, using demo set:", error?.message);
    } catch (e) {
      console.warn("[gl] Supabase unreachable, using demo supplements.", e);
    }
  }
  await wait(420);
  return { data: GL_SUPPLEMENTS, source: "demo" };
}
